# Generated by Django 4.2.11 on 2024-11-07 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_start', models.DateField()),
                ('rental_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('expired', 'EXPIRED')], default='pending', max_length=35)),
                ('agreement_signed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_start', models.DateField()),
                ('rental_end', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('agreement_signed', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_histories', to='cars.car')),
            ],
            options={
                'verbose_name': 'Rent History',
                'verbose_name_plural': 'Rent History',
                'db_table': 'rent_history',
            },
        ),
    ]
