# Generated by Django 4.2.11 on 2024-10-29 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_price_alter_car_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('rental_start', models.DateField()),
                ('rental_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('expired', 'EXPIRED')], default='pending', max_length=35)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carts', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
                'ordering': ['-created_at'],
            },
        ),
    ]
