# Generated by Django 4.2.11 on 2024-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.FloatField(),
        ),
    ]
