# Generated by Django 4.2.11 on 2024-10-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_price_alter_car_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
