# Generated by Django 4.2.11 on 2024-10-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverlicence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_id',
        ),
    ]
