# Generated by Django 4.2.11 on 2024-10-24 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blacklistedtoken_alter_review_car_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedtoken',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
