# Generated by Django 4.2.11 on 2024-10-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blacklistedtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedtoken',
            name='blacklisted_at',
        ),
    ]
