# Generated by Django 4.2.11 on 2024-10-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_blacklistedtoken_blacklisted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Blacklisted Token', 'verbose_name_plural': 'Blacklisted Tokens'},
        ),
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='blacklisted_token',
        ),
        migrations.AlterModelTable(
            name='driverlicence',
            table='driver_licence',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
