# Generated by Django 4.2.11 on 2024-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_blacklistedtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='passports/'),
        ),
    ]
