# Generated by Django 4.2.11 on 2024-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_passport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'SUPER_ADMIN'), ('company_admin', 'COMPANY_ADMIN'), ('user', 'USER')], default='user', max_length=40),
        ),
    ]
