# Generated by Django 4.2.11 on 2024-11-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicence',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='driver_licence/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'SUPER_ADMIN'), ('company_admin', 'COMPANY_ADMIN'), ('staff', 'STAFF'), ('user', 'USER')], default='user', max_length=40),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
