# Generated by Django 4.2.11 on 2024-10-15 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('four_digits', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=5)),
                ('hashed_cvv', models.CharField(max_length=64)),
                ('encrypted_number', models.BinaryField(default=None)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD')], default='cash', max_length=25)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=25)),
                ('currency', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD'), ('eur', 'EUR')], default='uzs', max_length=25)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.card')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
