# Generated by Django 4.2.11 on 2024-10-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
