# Generated by Django 4.2.11 on 2024-11-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_card_table_alter_transaction_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='encrypted_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='hashed_cvv',
        ),
    ]
