# Generated by Django 4.2.11 on 2024-11-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_card_encrypted_number_remove_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='token',
            field=models.CharField(blank=True),
        ),
    ]
